# Generated by Django 3.2.6 on 2021-10-21 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostandfound', '0003_lostpet_picture_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_found', models.CharField(max_length=50)),
                ('location_found', models.CharField(max_length=30)),
                ('description_found', models.TextField()),
                ('date_found', models.DateField()),
                ('post_date_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_found', models.BigIntegerField()),
                ('picture_found', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Image')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
