# Generated by Django 3.2.6 on 2021-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0007_lostperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostperson',
            name='per_reward_lost',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
